spring.application.name=repair-service
spring.datasource.url=jdbc:postgresql://localhost:5432/repair_db
spring.datasource.username=postgres
spring.datasource.password=i6pn9qv1m!>#+R%
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update